// cjy-blog-upload/web/src/views/TagsView.vue
<template>
  <div class="tags-page">
    <div class="list-page-header">
      <h1 class="list-page-title">{{ tag ? '# ' + tag : '标签' }}</h1>
      <p class="list-page-desc">{{ tag ? '包含该标签的全部内容' : '按标签浏览所有内容' }}</p>
    </div>

    <!-- 标签云 -->
    <div v-if="!tag" class="tag-cloud">
      <router-link v-for="t in tagList" :key="t.name" class="tag" :to="'/tags/' + encodeURIComponent(t.name)">
        {{ t.name }}<span class="tag-count">{{ t.count }}</span>
      </router-link>
      <div v-if="!tagList.length" class="empty-state" style="width:100%">
        还没有任何标签
        <span class="empty-mono">在 Markdown 的 frontmatter 里写 tags: [xxx] 即可</span>
      </div>
    </div>

    <!-- 某标签下的内容 -->
    <template v-else>
      <div class="list-count">// {{ entries.length }} 篇</div>
      <div v-if="entries.length" class="card-list">
        <EntryCard v-for="e in entries" :key="e.section + '/' + e.slug" :section="e.section" :item="e" />
      </div>
      <div v-else class="empty-state">没有找到相关内容</div>
    </template>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../api/client'
import EntryCard from '../components/EntryCard.vue'

const props = defineProps({
  tag: { type: String, default: '' }
})

const tagsMap = ref({})

const tagList = computed(() =>
  Object.keys(tagsMap.value)
    .map((name) => ({ name, count: tagsMap.value[name].length }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name))
)

const entries = computed(() => {
  if (!props.tag || !tagsMap.value[props.tag]) return []
  return [...tagsMap.value[props.tag]].sort((a, b) => (b.date || '').localeCompare(a.date || ''))
})

onMounted(async () => {
  try {
    tagsMap.value = await api.tags()
  } catch (e) {
    console.error(e)
  }
})
</script>

// web/src/views/TagsView.jsx
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Col, Empty, Row, Tag, Typography } from 'antd'
import { api } from '../api/client'
import EntryCard from '../components/EntryCard'

export default function TagsView() {
  const { tag } = useParams()
  const navigate = useNavigate()
  const [tagsMap, setTagsMap] = useState({})

  useEffect(() => { api.tags().then(setTagsMap).catch(() => {}) }, [])

  const tagList = useMemo(
    () => Object.keys(tagsMap)
      .map((name) => ({ name, count: tagsMap[name].length }))
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name)),
    [tagsMap]
  )

  const entries = useMemo(() => {
    if (!tag || !tagsMap[tag]) return []
    return [...tagsMap[tag]].sort((a, b) => (b.date || '').localeCompare(a.date || ''))
  }, [tag, tagsMap])

  return (
    <div className="tags-page">
      <div className="page-head">
        <Typography.Title level={2} style={{ marginBottom: 4 }}>{tag ? '# ' + tag : '标签'}</Typography.Title>
        <p className="page-desc">{tag ? '包含该标签的全部内容' : '按标签浏览所有内容'}</p>
      </div>

      {!tag ? (
        tagList.length ? (
          <div className="tag-cloud">
            {tagList.map((t) => (
              <Tag key={t.name} className="cloud-tag" onClick={() => navigate('/tags/' + encodeURIComponent(t.name))}>
                {t.name}<span className="cloud-count">{t.count}</span>
              </Tag>
            ))}
          </div>
        ) : (
          <Empty description="还没有任何标签" />
        )
      ) : (
        <>
          <div className="list-count">共 {entries.length} 篇</div>
          {entries.length ? (
            <Row gutter={[16, 16]}>
              {entries.map((e) => (
                <Col key={e.section + '/' + e.slug} xs={24} sm={12} xl={8}>
                  <EntryCard section={e.section} item={e} />
                </Col>
              ))}
            </Row>
          ) : (
            <Empty description="没有找到相关内容" />
          )}
        </>
      )}
    </div>
  )
}
