// web/src/components/EntryCard.jsx
import { Link } from 'react-router-dom'
import { Card, Tag } from 'antd'
import { formatDate, SECTIONS } from '../api/client'

// 通用条目卡片：有外链（如 GitHub 仓库）时点击直达外链，否则进入站内文章
export default function EntryCard({ section, item }) {
  const sectionName = SECTIONS[section] ? SECTIONS[section].name : section

  const card = (
    <Card className="entry-card" hoverable>
      <div className="entry-card-header">
        <span className="entry-card-title">{item.title}</span>
        {item.link && <Tag color="success" className="entry-badge">↗ repo</Tag>}
        {item.pinned && <Tag color="warning" className="entry-badge">置顶</Tag>}
      </div>
      <div className="entry-card-meta">
        <span>{sectionName}</span>
        {item.date && <span>{formatDate(item.date)}</span>}
        {item.link && <span className="meta-link">{item.link.replace(/^https?:\/\//, '')}</span>}
      </div>
      {item.summary && <p className="entry-card-summary">{item.summary}</p>}
      <div className="entry-card-tags">
        {(item.tags || []).map((t) => <Tag key={t}>{t}</Tag>)}
      </div>
    </Card>
  )

  return item.link ? (
    <a className="entry-card-link" href={item.link} target="_blank" rel="noopener noreferrer">{card}</a>
  ) : (
    <Link className="entry-card-link" to={'/' + section + '/' + encodeURIComponent(item.slug)}>{card}</Link>
  )
}

// web/src/components/EntryCard.vue
<template>
  <!-- 有外链（如 GitHub 仓库）时，卡片直接跳转外链 -->
  <a v-if="item.link" class="entry-card" :href="item.link" target="_blank" rel="noopener">
    <div class="entry-card-header">
      <span class="entry-card-title">{{ item.title }}</span>
      <span class="link-badge">↗ repo</span>
      <span v-if="item.pinned" class="pin-badge">pinned</span>
    </div>
    <div class="entry-card-meta">
      <span>{{ sectionName }}</span>
      <span v-if="item.date">{{ formatDate(item.date) }}</span>
      <span class="meta-link">{{ item.link.replace(/^https?:\/\//, '') }}</span>
    </div>
    <p v-if="item.summary" class="entry-card-summary">{{ item.summary }}</p>
    <div class="entry-card-tags">
      <span v-for="t in item.tags" :key="t" class="tag">{{ t }}</span>
    </div>
  </a>

  <router-link v-else class="entry-card" :to="'/' + section + '/' + encodeURIComponent(item.slug)">
    <div class="entry-card-header">
      <span class="entry-card-title">{{ item.title }}</span>
      <span v-if="item.pinned" class="pin-badge">pinned</span>
    </div>
    <div class="entry-card-meta">
      <span>{{ sectionName }}</span>
      <span v-if="item.date">{{ formatDate(item.date) }}</span>
    </div>
    <p v-if="item.summary" class="entry-card-summary">{{ item.summary }}</p>
    <div class="entry-card-tags">
      <span v-for="t in item.tags" :key="t" class="tag">{{ t }}</span>
    </div>
  </router-link>
</template>

<script setup>
import { computed } from 'vue'
import { formatDate, SECTIONS } from '../api/client'

const props = defineProps({
  section: { type: String, required: true },
  item: { type: Object, required: true }
})

const sectionName = computed(() => (SECTIONS[props.section] ? SECTIONS[props.section].name : props.section))
</script>
